# # use your own native target
[target.x86_64-pc-windows-msvc]
rustflags = ["-Csymbol-mangling-version=v0"]
# rustflags = ["--cfg", "erase_components"]


# [target.wasm32-unknown-unknown]
# rustflags = ["--cfg", "erase_components"]
